### ISSUE TITLE
咨询一个关于动态换肤的处理优化

### ISSUE THREAD

**Issue by cxMax** [drakeet/rebase-android#11]
咨询一个关于动态换肤的问题.
1.rebase-android里面的方案是apply theme style ,activity.recreate
可不可以activity不recreate,从而达到在activity动态换肤的目的呢?
ps:
参考了下github star比较多的两个colorful项目
1.1个是在application层面apply theme,在activity调用是无效的
2.另一个虽然能在activity层面动态改变theme,但有所限制,1是必须在oncreate()调用,2是使用colorsetter一一改变布局中控件的颜色,虽然繁琐但是能够达到效果.
因此,我想问一下作者有没有更好的换肤方案呢?  有的话麻烦推荐一下,一个链接都行.
谢谢啦~
btw, 期待MultiType 3.0

**Comment by drakeet** [comment]
感谢！但 rebase-android 不是意在成为一个换肤项目或类库，它是一个综合型客户端。当前其使用的 Colorful 也只是我分分钟自我创建出来的一套换肤方案，有许多可改善得更好的空间，但这不是 rebase-android 的主要任务，在没有业务或场景需求的情况下，本着简单、够用的原则，它不会大力发展这个换肤方案。至于开源社区中其他的换肤方案，我曾经看过几个，要么太复杂，要么自定义程度十分有限（比如仅限于 colorPrimary 之类的颜色值进行更新。我的换肤方案采用了十分简单而且可定制性很高的策略，虽然它是一个换肤方案，**但也是可以用于改变布局中的各个尺寸**、改变 content styles，对我来说，足够了。

**Comment by drakeet** [comment]
另外 `recreate` 有什么问题吗？何必排斥呢？`recreate` 是十分好的方式。

**Comment by drakeet** [comment]
因为我只是想随手实现换肤功能，或者说换肤功能当前不是很紧要，而且实现起来也不是一件难事，因此我并不打算引入第三方方案使得代码变得复杂或失去自我。

另外，我们目前的换肤方案本身是不错的。各个类角色或者说 API 设计清晰合适，也实现了与 layout/value 文件天然配合，不脱离于资源文件，不往 native 写入颜色值，可谓各司其职，感觉是很不错的 :P

**Comment by drakeet** [comment]
因为你说要我帮忙推荐，于是我刚去帮忙考察了几个很久之前标记过的开源换肤方案，包括 hehonghui/Colorful 和 garretyoder/Colorful，都很不错，而且很巧的是，hehonghui 版的和我可谓不约而同，都采用了 ?attr 方式。

因此我得声明一下 :P，在实现我的换肤方法之前，我并没有去看过他人的方案或代码，可能很久很久粗略看过他们的文档，但也几乎全忘光了，只记得谁谁实现过这类东西。另外，我也是刻意在实现之前不去看他们的视线方式，避免思维被局限住——这也说明了，实现这么一个东西实际上不是难事，要做到完全的自由，还得自己进行实现。

以上，不知道能否回答你的问题，供以借鉴。

**Comment by cxMax** [comment]
谢谢这么细致 , 耐心的回答 .
非常感谢能分享思考问题的切入点 以及 实现思路.
确实受教了, 谢谢啦 ^ ^

**Comment by iamwent** [comment]
Good question, and great anwser!
