### ISSUE TITLE
加载更多在分页的时候会卡顿一下

### ISSUE THREAD

**Issue by ssyijiu** [drakeet/rebase-android#14]
仔细看了 LoadMoreDelegate 这个类，感觉很棒，这种没有 footer 的加载更多在用户滑动慢的时候体验很好。可是在用力滑一下让列表自己 "飞" 起来的时候，在加载下一页的地方由于网络延时就会停顿下来， Tweet 这一栏现在一共 24 条数据，现在的接口每次请求的 30 条数据所以不会有感觉，改成 20 后现象很明显。

**Comment by drakeet** [comment]
嗯，这是交互问题，不是代码问题，可以考虑加一个 footer 来显示加载中 : )

**Comment by ssyijiu** [comment]
恩，如果你以后考虑加 footer 的话希望能 @ 我一下。
